/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#fcf9f8",
        "on-secondary-fixed": "#2c1600",
        "secondary-fixed": "#ffdcbd",
        "surface-container": "#f0eded",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#ffb3ae",
        "background": "#fcf9f8",
        "inverse-primary": "#ffb3ae",
        "error": "#ba1a1a",
        "tertiary-fixed": "#e8e3cd",
        "on-tertiary-fixed": "#1e1c0f",
        "on-secondary-container": "#784f21",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#eae7e7",
        "on-primary-fixed-variant": "#6d3734",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#370d0c",
        "tertiary-fixed-dim": "#ccc7b2",
        "on-tertiary-container": "#888472",
        "inverse-surface": "#303030",
        "primary-container": "#370d0c",
        "surface-cream": "#FFF9E3",
        "primary": "#000000",
        "primary-fixed": "#ffdad7",
        "on-secondary-fixed-variant": "#643e12",
        "error-container": "#ffdad6",
        "on-surface-variant": "#524342",
        "inverse-on-surface": "#f3f0ef",
        "secondary-container": "#fdc48c",
        "surface-container-highest": "#e4e2e1",
        "tertiary-container": "#1e1c0f",
        "outline-variant": "#d7c2c0",
        "secondary-fixed-dim": "#f4bc84",
        "on-primary-container": "#b5726e",
        "neutral-light": "#F4F4F4",
        "surface-dim": "#dcd9d9",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#4a4737",
        "accent-gold": "#AD7D4B",
        "on-error-container": "#93000a",
        "on-background": "#1b1c1c",
        "surface-container-low": "#f6f3f2",
        "tertiary": "#000000",
        "surface-variant": "#e4e2e1",
        "ink-deep": "#340A0A",
        "surface-tint": "#8a4e4a",
        "secondary": "#7f5527",
        "on-surface": "#1b1c1c",
        "surface-bright": "#fcf9f8",
        "outline": "#857371",
        "brand": {
          "DEFAULT": "#340a0a",
          "bg": "#fcf9f8",
          "text": "#222222",
          "gray": "#737373",
          "lightGray": "#f0f0f0",
          "border": "#e5e5e5"
        }
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "sm": "0.125rem",
        "md": "0.375rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "8px",
        "section-gap-lg": "120px",
        "margin-desktop": "64px",
        "container-max": "1440px",
        "section-gap-md": "80px",
        "gutter": "24px",
        "margin-mobile": "20px"
      },
      fontFamily: {
        "sans": ['"Hanken Grotesk"', 'sans-serif'],
        "serif": ['"Playfair Display"', 'serif'],
        "body-lg": ["Manrope", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "display-lg": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "label-sm": ["Hanken Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "label-bold": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": ["64px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.03em", fontWeight: "500" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "label-bold": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.01em", fontWeight: "600" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
