/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreRouteImport } from './routes/_store'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as OrderSuccessRouteImport } from './routes/order-success'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as StoreIndexRouteImport } from './routes/_store/index'
import { Route as StoreAboutRouteImport } from './routes/_store/about'
import { Route as StoreAccountRouteImport } from './routes/_store/account'
import { Route as StoreBestSellersRouteImport } from './routes/_store/best-sellers'
import { Route as StoreJewelryRouteImport } from './routes/_store/jewelry'
import { Route as StoreMenRouteImport } from './routes/_store/men'
import { Route as StoreNewArrivalsRouteImport } from './routes/_store/new-arrivals'
import { Route as StoreOuterwearRouteImport } from './routes/_store/outerwear'
import { Route as StoreWishlistRouteImport } from './routes/_store/wishlist'
import { Route as StoreWomenRouteImport } from './routes/_store/women'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminInventoryRouteImport } from './routes/admin/inventory'
import { Route as AdminMarketingRouteImport } from './routes/admin/marketing'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as StoreProductIdRouteImport } from './routes/_store/product.$id'
import { Route as AdminMarketingNewCouponRouteImport } from './routes/admin/marketing_.new-coupon'
import { Route as AdminProductsNewIndexRouteImport } from './routes/admin/products/new/index'
import { Route as AdminProductsNewSeoRouteImport } from './routes/admin/products/new/seo'
import { Route as AdminProductsNewVariantsRouteImport } from './routes/admin/products/new/variants'

const StoreRoute = StoreRouteImport.update({
  id: '/_store',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreRoute,
} as any)
const StoreAboutRoute = StoreAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => StoreRoute,
} as any)
const StoreAccountRoute = StoreAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => StoreRoute,
} as any)
const StoreBestSellersRoute = StoreBestSellersRouteImport.update({
  id: '/best-sellers',
  path: '/best-sellers',
  getParentRoute: () => StoreRoute,
} as any)
const StoreJewelryRoute = StoreJewelryRouteImport.update({
  id: '/jewelry',
  path: '/jewelry',
  getParentRoute: () => StoreRoute,
} as any)
const StoreMenRoute = StoreMenRouteImport.update({
  id: '/men',
  path: '/men',
  getParentRoute: () => StoreRoute,
} as any)
const StoreNewArrivalsRoute = StoreNewArrivalsRouteImport.update({
  id: '/new-arrivals',
  path: '/new-arrivals',
  getParentRoute: () => StoreRoute,
} as any)
const StoreOuterwearRoute = StoreOuterwearRouteImport.update({
  id: '/outerwear',
  path: '/outerwear',
  getParentRoute: () => StoreRoute,
} as any)
const StoreWishlistRoute = StoreWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => StoreRoute,
} as any)
const StoreWomenRoute = StoreWomenRouteImport.update({
  id: '/women',
  path: '/women',
  getParentRoute: () => StoreRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingRoute = AdminMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const StoreProductIdRoute = StoreProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => StoreRoute,
} as any)
const AdminMarketingNewCouponRoute = AdminMarketingNewCouponRouteImport.update({
  id: '/marketing_/new-coupon',
  path: '/marketing/new-coupon',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsNewIndexRoute = AdminProductsNewIndexRouteImport.update({
  id: '/products/new/',
  path: '/products/new/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsNewSeoRoute = AdminProductsNewSeoRouteImport.update({
  id: '/products/new/seo',
  path: '/products/new/seo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsNewVariantsRoute =
  AdminProductsNewVariantsRouteImport.update({
    id: '/products/new/variants',
    path: '/products/new/variants',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof StoreIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/order-success': typeof OrderSuccessRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/about': typeof StoreAboutRoute
  '/account': typeof StoreAccountRoute
  '/best-sellers': typeof StoreBestSellersRoute
  '/jewelry': typeof StoreJewelryRoute
  '/men': typeof StoreMenRoute
  '/new-arrivals': typeof StoreNewArrivalsRoute
  '/outerwear': typeof StoreOuterwearRoute
  '/wishlist': typeof StoreWishlistRoute
  '/women': typeof StoreWomenRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/product/$id': typeof StoreProductIdRoute
  '/admin/marketing/new-coupon': typeof AdminMarketingNewCouponRoute
  '/admin/products/new/seo': typeof AdminProductsNewSeoRoute
  '/admin/products/new/variants': typeof AdminProductsNewVariantsRoute
  '/admin/products/new/': typeof AdminProductsNewIndexRoute
}
export interface FileRoutesByTo {
  '/checkout': typeof CheckoutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/order-success': typeof OrderSuccessRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/about': typeof StoreAboutRoute
  '/account': typeof StoreAccountRoute
  '/best-sellers': typeof StoreBestSellersRoute
  '/jewelry': typeof StoreJewelryRoute
  '/men': typeof StoreMenRoute
  '/new-arrivals': typeof StoreNewArrivalsRoute
  '/outerwear': typeof StoreOuterwearRoute
  '/wishlist': typeof StoreWishlistRoute
  '/women': typeof StoreWomenRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/': typeof StoreIndexRoute
  '/admin': typeof AdminIndexRoute
  '/product/$id': typeof StoreProductIdRoute
  '/admin/marketing/new-coupon': typeof AdminMarketingNewCouponRoute
  '/admin/products/new/seo': typeof AdminProductsNewSeoRoute
  '/admin/products/new/variants': typeof AdminProductsNewVariantsRoute
  '/admin/products/new': typeof AdminProductsNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_store': typeof StoreRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/order-success': typeof OrderSuccessRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_store/about': typeof StoreAboutRoute
  '/_store/account': typeof StoreAccountRoute
  '/_store/best-sellers': typeof StoreBestSellersRoute
  '/_store/jewelry': typeof StoreJewelryRoute
  '/_store/men': typeof StoreMenRoute
  '/_store/new-arrivals': typeof StoreNewArrivalsRoute
  '/_store/outerwear': typeof StoreOuterwearRoute
  '/_store/wishlist': typeof StoreWishlistRoute
  '/_store/women': typeof StoreWomenRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/_store/': typeof StoreIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_store/product/$id': typeof StoreProductIdRoute
  '/admin/marketing_/new-coupon': typeof AdminMarketingNewCouponRoute
  '/admin/products/new/seo': typeof AdminProductsNewSeoRoute
  '/admin/products/new/variants': typeof AdminProductsNewVariantsRoute
  '/admin/products/new/': typeof AdminProductsNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkout'
    | '/forgot-password'
    | '/order-success'
    | '/sign-in'
    | '/sign-up'
    | '/about'
    | '/account'
    | '/best-sellers'
    | '/jewelry'
    | '/men'
    | '/new-arrivals'
    | '/outerwear'
    | '/wishlist'
    | '/women'
    | '/admin/analytics'
    | '/admin/customers'
    | '/admin/inventory'
    | '/admin/marketing'
    | '/admin/orders'
    | '/admin/settings'
    | '/admin/'
    | '/product/$id'
    | '/admin/marketing/new-coupon'
    | '/admin/products/new/seo'
    | '/admin/products/new/variants'
    | '/admin/products/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/checkout'
    | '/forgot-password'
    | '/order-success'
    | '/sign-in'
    | '/sign-up'
    | '/about'
    | '/account'
    | '/best-sellers'
    | '/jewelry'
    | '/men'
    | '/new-arrivals'
    | '/outerwear'
    | '/wishlist'
    | '/women'
    | '/admin/analytics'
    | '/admin/customers'
    | '/admin/inventory'
    | '/admin/marketing'
    | '/admin/orders'
    | '/admin/settings'
    | '/'
    | '/admin'
    | '/product/$id'
    | '/admin/marketing/new-coupon'
    | '/admin/products/new/seo'
    | '/admin/products/new/variants'
    | '/admin/products/new'
  id:
    | '__root__'
    | '/_store'
    | '/admin'
    | '/checkout'
    | '/forgot-password'
    | '/order-success'
    | '/sign-in'
    | '/sign-up'
    | '/_store/about'
    | '/_store/account'
    | '/_store/best-sellers'
    | '/_store/jewelry'
    | '/_store/men'
    | '/_store/new-arrivals'
    | '/_store/outerwear'
    | '/_store/wishlist'
    | '/_store/women'
    | '/admin/analytics'
    | '/admin/customers'
    | '/admin/inventory'
    | '/admin/marketing'
    | '/admin/orders'
    | '/admin/settings'
    | '/_store/'
    | '/admin/'
    | '/_store/product/$id'
    | '/admin/marketing_/new-coupon'
    | '/admin/products/new/seo'
    | '/admin/products/new/variants'
    | '/admin/products/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  StoreRoute: typeof StoreRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  OrderSuccessRoute: typeof OrderSuccessRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_store': {
      id: '/_store'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success': {
      id: '/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_store/': {
      id: '/_store/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/about': {
      id: '/_store/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof StoreAboutRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/account': {
      id: '/_store/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof StoreAccountRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/best-sellers': {
      id: '/_store/best-sellers'
      path: '/best-sellers'
      fullPath: '/best-sellers'
      preLoaderRoute: typeof StoreBestSellersRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/jewelry': {
      id: '/_store/jewelry'
      path: '/jewelry'
      fullPath: '/jewelry'
      preLoaderRoute: typeof StoreJewelryRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/men': {
      id: '/_store/men'
      path: '/men'
      fullPath: '/men'
      preLoaderRoute: typeof StoreMenRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/new-arrivals': {
      id: '/_store/new-arrivals'
      path: '/new-arrivals'
      fullPath: '/new-arrivals'
      preLoaderRoute: typeof StoreNewArrivalsRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/outerwear': {
      id: '/_store/outerwear'
      path: '/outerwear'
      fullPath: '/outerwear'
      preLoaderRoute: typeof StoreOuterwearRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/wishlist': {
      id: '/_store/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof StoreWishlistRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/women': {
      id: '/_store/women'
      path: '/women'
      fullPath: '/women'
      preLoaderRoute: typeof StoreWomenRouteImport
      parentRoute: typeof StoreRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing': {
      id: '/admin/marketing'
      path: '/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AdminMarketingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_store/product/$id': {
      id: '/_store/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof StoreProductIdRouteImport
      parentRoute: typeof StoreRoute
    }
    '/admin/marketing_/new-coupon': {
      id: '/admin/marketing_/new-coupon'
      path: '/marketing/new-coupon'
      fullPath: '/admin/marketing/new-coupon'
      preLoaderRoute: typeof AdminMarketingNewCouponRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/new/': {
      id: '/admin/products/new/'
      path: '/products/new'
      fullPath: '/admin/products/new/'
      preLoaderRoute: typeof AdminProductsNewIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/new/seo': {
      id: '/admin/products/new/seo'
      path: '/products/new/seo'
      fullPath: '/admin/products/new/seo'
      preLoaderRoute: typeof AdminProductsNewSeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/new/variants': {
      id: '/admin/products/new/variants'
      path: '/products/new/variants'
      fullPath: '/admin/products/new/variants'
      preLoaderRoute: typeof AdminProductsNewVariantsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface StoreRouteChildren {
  StoreAboutRoute: typeof StoreAboutRoute
  StoreAccountRoute: typeof StoreAccountRoute
  StoreBestSellersRoute: typeof StoreBestSellersRoute
  StoreJewelryRoute: typeof StoreJewelryRoute
  StoreMenRoute: typeof StoreMenRoute
  StoreNewArrivalsRoute: typeof StoreNewArrivalsRoute
  StoreOuterwearRoute: typeof StoreOuterwearRoute
  StoreWishlistRoute: typeof StoreWishlistRoute
  StoreWomenRoute: typeof StoreWomenRoute
  StoreIndexRoute: typeof StoreIndexRoute
  StoreProductIdRoute: typeof StoreProductIdRoute
}

const StoreRouteChildren: StoreRouteChildren = {
  StoreAboutRoute: StoreAboutRoute,
  StoreAccountRoute: StoreAccountRoute,
  StoreBestSellersRoute: StoreBestSellersRoute,
  StoreJewelryRoute: StoreJewelryRoute,
  StoreMenRoute: StoreMenRoute,
  StoreNewArrivalsRoute: StoreNewArrivalsRoute,
  StoreOuterwearRoute: StoreOuterwearRoute,
  StoreWishlistRoute: StoreWishlistRoute,
  StoreWomenRoute: StoreWomenRoute,
  StoreIndexRoute: StoreIndexRoute,
  StoreProductIdRoute: StoreProductIdRoute,
}

const StoreRouteWithChildren = StoreRoute._addFileChildren(StoreRouteChildren)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminMarketingRoute: typeof AdminMarketingRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminMarketingNewCouponRoute: typeof AdminMarketingNewCouponRoute
  AdminProductsNewSeoRoute: typeof AdminProductsNewSeoRoute
  AdminProductsNewVariantsRoute: typeof AdminProductsNewVariantsRoute
  AdminProductsNewIndexRoute: typeof AdminProductsNewIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminMarketingRoute: AdminMarketingRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminMarketingNewCouponRoute: AdminMarketingNewCouponRoute,
  AdminProductsNewSeoRoute: AdminProductsNewSeoRoute,
  AdminProductsNewVariantsRoute: AdminProductsNewVariantsRoute,
  AdminProductsNewIndexRoute: AdminProductsNewIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  StoreRoute: StoreRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  OrderSuccessRoute: OrderSuccessRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
